label: 'mediator-acapy'
endpoint:
  - 'http://localhost:8010'
  - 'ws://localhost:8000'
inbound-transport:
  - [http, 0.0.0.0, 8010]
  - [ws, 0.0.0.0, 8000]
outbound-transport:
  - http
  - ws
admin: [0.0.0.0, 8001]
admin-api-key: ${ADMIN_API_KEY}
wallet-type: askar
wallet-name: base_wallet
wallet-key: ${WALLET_KEY}
wallet-storage-type: sqlite
wallet-storage-config: '{"path":"/data/base_wallet.db"}'
auto-provision: true
no-ledger: true
jwt-secret: ${JWT_SECRET}
auto-accept-invites: true
auto-accept-requests: true
auto-respond-credential-proposal: true
auto-respond-credential-offer: true
auto-respond-credential-request: true
auto-respond-presentation-request: true
auto-verify-presentation: true
invite-multi-use: true
enable-undelivered-queue: true
emit-new-didcomm-prefix: true
emit-new-didcomm-mime-type: true
auto-ping-connection: true
open-mediation: true
log-level: debug
